# Generated by Django 3.2.18 on 2023-04-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(fields=('user', 'guest_name'), name='unique guest for each user'),
        ),
    ]
