# Generated by Django 3.2.18 on 2023-03-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0002_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='message',
            new_name='message_to_couple',
        ),
        migrations.AlterField(
            model_name='guest',
            name='is_attending',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default='', null=True, verbose_name='Attending?'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='plus_one_attending',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True, verbose_name='Plus one?'),
        ),
    ]
