# Generated by Django 3.2.18 on 2023-03-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0003_auto_20230309_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='is_attending',
            new_name='attending',
        ),
    ]
