# Generated by Django 3.2.18 on 2023-03-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0004_rename_is_attending_guest_attending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['guest_name']},
        ),
    ]
