# Generated by Django 3.2.18 on 2023-04-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0012_auto_20230328_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='event',
        ),
    ]
